[2024-02-06T02:46:49.726+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Read_and_load_of_API_to_MySQLDB.Load_companies_registers manual__2024-02-06T02:26:39.564943+00:00 [queued]>
[2024-02-06T02:46:49.746+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Read_and_load_of_API_to_MySQLDB.Load_companies_registers manual__2024-02-06T02:26:39.564943+00:00 [queued]>
[2024-02-06T02:46:49.748+0000] {taskinstance.py:2170} INFO - Starting attempt 17 of 20
[2024-02-06T02:46:49.774+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): Load_companies_registers> on 2024-02-06 02:26:39.564943+00:00
[2024-02-06T02:46:49.781+0000] {standard_task_runner.py:60} INFO - Started process 953 to run task
[2024-02-06T02:46:49.785+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Read_and_load_of_API_to_MySQLDB', 'Load_companies_registers', 'manual__2024-02-06T02:26:39.564943+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/CRM.py', '--cfg-path', '/tmp/tmpqxpna4dj']
[2024-02-06T02:46:49.788+0000] {standard_task_runner.py:88} INFO - Job 124: Subtask Load_companies_registers
[2024-02-06T02:46:49.863+0000] {task_command.py:423} INFO - Running <TaskInstance: Read_and_load_of_API_to_MySQLDB.Load_companies_registers manual__2024-02-06T02:26:39.564943+00:00 [running]> on host 648978c3a8b9
[2024-02-06T02:46:49.997+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jmoc' AIRFLOW_CTX_DAG_ID='Read_and_load_of_API_to_MySQLDB' AIRFLOW_CTX_TASK_ID='Load_companies_registers' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T02:26:39.564943+00:00' AIRFLOW_CTX_TRY_NUMBER='17' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-06T02:26:39.564943+00:00'
[2024-02-06T02:46:50.031+0000] {base.py:83} INFO - Using connection ID 'mysql_connection' for task execution.
[2024-02-06T02:46:50.048+0000] {sql.py:450} INFO - Running statement: INSERT IGNORE INTO companies VALUES ('Romaguera-Crona','Multi-layered client-server neural-net', 'harness real-time e-markets'), parameters: None
[2024-02-06T02:46:50.052+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/CRM.py", line 77, in Load_companies_registers
    company_register.save()
  File "/opt/airflow/dags/models/Company.py", line 15, in save
    hook.run(mysql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1046, 'No database selected')
[2024-02-06T02:46:50.077+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Read_and_load_of_API_to_MySQLDB, task_id=Load_companies_registers, execution_date=20240206T022639, start_date=20240206T024649, end_date=20240206T024650
[2024-02-06T02:46:50.095+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 124 for task Load_companies_registers ((1046, 'No database selected'); 953)
[2024-02-06T02:46:50.118+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-06T02:46:50.146+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
