[2024-02-06T19:22:49.344+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Read_and_load_of_API_to_MySQLDB.Load_users_registers manual__2024-02-06T03:05:04.018386+00:00 [queued]>
[2024-02-06T19:22:49.365+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Read_and_load_of_API_to_MySQLDB.Load_users_registers manual__2024-02-06T03:05:04.018386+00:00 [queued]>
[2024-02-06T19:22:49.367+0000] {taskinstance.py:2170} INFO - Starting attempt 21 of 26
[2024-02-06T19:22:49.398+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): Load_users_registers> on 2024-02-06 03:05:04.018386+00:00
[2024-02-06T19:22:49.407+0000] {standard_task_runner.py:60} INFO - Started process 1040 to run task
[2024-02-06T19:22:49.415+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Read_and_load_of_API_to_MySQLDB', 'Load_users_registers', 'manual__2024-02-06T03:05:04.018386+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/CRM.py', '--cfg-path', '/tmp/tmps6n1uk_v']
[2024-02-06T19:22:49.418+0000] {standard_task_runner.py:88} INFO - Job 190: Subtask Load_users_registers
[2024-02-06T19:22:49.521+0000] {task_command.py:423} INFO - Running <TaskInstance: Read_and_load_of_API_to_MySQLDB.Load_users_registers manual__2024-02-06T03:05:04.018386+00:00 [running]> on host 648978c3a8b9
[2024-02-06T19:22:49.711+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='jmoc' AIRFLOW_CTX_DAG_ID='Read_and_load_of_API_to_MySQLDB' AIRFLOW_CTX_TASK_ID='Load_users_registers' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T03:05:04.018386+00:00' AIRFLOW_CTX_TRY_NUMBER='21' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-06T03:05:04.018386+00:00'
[2024-02-06T19:22:49.746+0000] {base.py:83} INFO - Using connection ID 'mysql_connection' for task execution.
[2024-02-06T19:22:49.764+0000] {sql.py:450} INFO - Running statement: SELECT id FROM ***_PI.cities WHERE name = 'Gwenborough', parameters: None
[2024-02-06T19:22:49.766+0000] {sql.py:459} INFO - Rows affected: 1
[2024-02-06T19:22:49.778+0000] {base.py:83} INFO - Using connection ID 'mysql_connection' for task execution.
[2024-02-06T19:22:49.787+0000] {sql.py:450} INFO - Running statement: SELECT id FROM ***_PI.companies WHERE name = 'Romaguera-Crona', parameters: None
[2024-02-06T19:22:49.788+0000] {sql.py:459} INFO - Rows affected: 1
[2024-02-06T19:22:49.793+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/CRM.py", line 92, in Load_users_registers
    user_register = User(x)
  File "/opt/airflow/dags/models/User.py", line 6, in __init__
    self.__name = body.name,
AttributeError: 'dict' object has no attribute 'name'
[2024-02-06T19:22:49.821+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Read_and_load_of_API_to_MySQLDB, task_id=Load_users_registers, execution_date=20240206T030504, start_date=20240206T192249, end_date=20240206T192249
[2024-02-06T19:22:49.849+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 190 for task Load_users_registers ('dict' object has no attribute 'name'; 1040)
[2024-02-06T19:22:49.869+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-06T19:22:49.902+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
